### ISSUE TITLE
datalad get downloads fail without asking credientials in first place

### ISSUE THREAD

**Issue by jasonbian97** [datalad-datasets/human-connectome-project-openaccess#30]
Hi, I run the `datalad get` command for the first time, however, it does not ask me for the credentials and directly start downloading:

![image](https://user-images.githubusercontent.com/47854957/142965173-ccae3f1f-51d1-43d9-b1ad-a43bc16d8460.png)

And it fails:

![image](https://user-images.githubusercontent.com/47854957/142965457-578178ff-329c-45d3-8308-a267498d2807.png)

Any thoughts?

Thanks for your help!

**Comment by adswa** [comment]
Could you paste the output of ``datalad wtf`` into this issue? It would be good to know which software versions you're using.

**Comment by adswa** [comment]
It would also be good to get the output of the same call with log level debug (``datalad -l debug get 814548``). I coincidentally just received a report with a ``RunTimeError`` as well where on first sight the cause seems to be a problem with the keyring, but that only showed up in the debug log.

**Comment by jasonbian97** [comment]
Thanks for your reply! The output is very long, so I uploaded them here as txt file:
`datalad wtf` https://github.com/jasonbian97/human-connectome-project-openaccess/blob/master/wtf.txt
`datalad -l debug get 814548` https://github.com/jasonbian97/human-connectome-project-openaccess/blob/master/debug_datalad_get_debug.txt
I also received `RuntimeError` as you can see in the second txt file.

**Comment by adswa** [comment]
Thanks! On first sight, this all looks ok. Its not cool that there is no clear indication of what is wrong, and that it also doesn't seem to re-prompt for credentials. I will make a dedicated issue for this in the datalad core repository. One way I can reproduce this is by having stored wrong credentials. Could you make sure that there are no hcp related wrong credentials in your keyring? On Linux, you may have ``seahorse``, and you could check for ``datalad-hcp-s3``:
![Screenshot from 2021-11-24 09-10-35](https://user-images.githubusercontent.com/29738718/143199634-da457528-c623-4c83-a0a8-f5156f8e2b62.png)
Otherwise, you could try to set them explicitly via the ``keyring`` Python interface (see the box "Resetting AWS credentials" at http://handbook.datalad.org/en/latest/usecases/HCP_dataset.html).
It would also be cool if you could try to retrieve the files with your AWS credentials set as environment variables and see if that works. This would look like this:

```
DATALAD_hcp_s3_key_id=YOURKEYHERE  DATALAD_hcp_s3_secret_id=YOUR SECRETIDHERE datalad get HCP1200/100307/...
```

**Comment by jajcayn** [comment]
Hey, 
I am having a similar problem. I started a new virtual machine (Ubuntu), installed `datalad` and tried to download some MEG data, same issue. `datalad` never asked for my credentials and even when I try to add them explicitly by 
```bash
DATALAD_hcp_s3_key_id=YOURKEYHERE  DATALAD_hcp_s3_secret_id=YOUR SECRETIDHERE datalad get ...
```
still having the same runtime error.
<details>
<summary>datalad wtf</summary>

```
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials
  - keyring:
    - active_backends:
      - SecretService Keyring
      - EncryptedKeyring with [PBKDF2] AES256.CFB v.1.0 at /home/ubuntu/.local/share/python_keyring/crypted_pass.cfg
      - PlaintextKeyring with no encyption v.1.0 at /home/ubuntu/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/ubuntu/.local/share/python_keyring/keyringrc.cfg
    - data_root: /home/ubuntu/.local/share/python_keyring
## datalad
  - version: 0.15.3
## dataset
  - branches:
    - git-annex@034811f
    - master@3e6f4b0
  - id: 2d7426a2-3b5f-11ea-96db-0025904abcb0
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG
  - repo: AnnexRepo
## dependencies
  - annexremote: 1.4.3
  - appdirs: 1.4.3
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 8.20211123+git12-g02e3756bd-1~ndall+1
  - cmd:bundled-git: 2.30.2
  - cmd:git: 2.30.2
  - cmd:system-git: 2.25.1
  - cmd:system-ssh: 8.2p1
  - exifread: 2.1.2
  - humanize: 1.0.0
  - iso8601: 0.1.12
  - keyring: 18.0.1
  - keyrings.alt: 3.4.0
  - msgpack: 0.6.2
  - mutagen: 1.44.0
  - requests: 2.22.0
  - wrapt: 1.11.2
## environment
  - LANG: C.UTF-8
  - LC_ALL: en_US.UTF-8
  - LC_CTYPE: UTF-8
  - LC_TERMINAL: iTerm2
  - LC_TERMINAL_VERSION: 3.4.14
  - PATH: /home/ubuntu/.pyenv/shims:/home/ubuntu/.pyenv/shims:/home/ubuntu/.pyenv/plugins/pyenv-virtualenv/shims:/home/ubuntu/.pyenv/shims:/home/ubuntu/.local/bin:/home/ubuntu/.pyenv/plugins/pyenv-virtualenv/shims:/home/ubuntu/.pyenv/bin:/home/ubuntu/.pyenv/bin:/home/ubuntu/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
## extensions
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions:
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.26
    - DAV-1.3.4
    - feed-1.3.0.1
    - ghc-8.8.4
    - http-client-0.6.4.1
    - persistent-sqlite-2.10.6.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.1.0
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - local repository version: 8
  - operating system: linux x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions:
    - 8
  - upgrade supported from repository versions:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20211123+git12-g02e3756bd-1~ndall+1
## location
  - path: /mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG
  - type: dataset
## metadata_extractors
  - annex (datalad 0.15.3):
    - distribution: datalad 0.15.3
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.15.3):
    - distribution: datalad 0.15.3
    - load_error: None
    - module: datalad.metadata.extractors.audio
    - version: None
  - datacite (datalad 0.15.3):
    - distribution: datalad 0.15.3
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.15.3):
    - distribution: datalad 0.15.3
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.15.3):
    - distribution: datalad 0.15.3
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif (datalad 0.15.3):
    - distribution: datalad 0.15.3
    - load_error: None
    - module: datalad.metadata.extractors.exif
    - version: None
  - frictionless_datapackage (datalad 0.15.3):
    - distribution: datalad 0.15.3
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.15.3):
    - distribution: datalad 0.15.3
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp (datalad 0.15.3):
    - distribution: datalad 0.15.3
    - load_error: ModuleNotFoundError(No module named 'libxmp')
    - module: datalad.metadata.extractors.xmp
## metadata_indexers
## python
  - implementation: CPython
  - version: 3.8.10
## system
  - distribution: ubuntu/20.04/focal
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 339
  - name: Linux
  - release: 5.4.0-91-generic
  - type: posix
  - version: #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021
```
</details>

<details>
<summary>datalad -l debug</summary>

```
[DEBUG  ] Command line args 1st pass for DataLad 0.15.3. Parsed: Namespace() Unparsed: ['get', '100307_MEG_3-Restin_rmegpreproc.mat']
[DEBUG  ] Building doc for <class 'datalad.local.subdatasets.Subdatasets'>
[DEBUG  ] Building doc for <class 'datalad.core.distributed.clone.Clone'>
[DEBUG  ] Building doc for <class 'datalad.distribution.get.Get'>
[DEBUG  ] Parsing known args among ['/usr/bin/datalad', '-l', 'debug', 'get', '100307_MEG_3-Restin_rmegpreproc.mat']
[DEBUG  ] Run ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin'] (cwd=None)
[DEBUG  ] Finished ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin'] with status 0
[DEBUG  ] Determined class of decorated function: <class 'datalad.distribution.get.Get'>
[DEBUG  ] Resolved dataset to get content of <<['100307_MEG_3++21 chars++at']>>: /mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG
[DEBUG  ] Run ['git', 'config', '-z', '-l', '--show-origin'] (cwd=/mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG)
[DEBUG  ] Finished ['git', 'config', '-z', '-l', '--show-origin'] with status 0
[DEBUG  ] Run ['git', 'config', '-z', '-l', '--show-origin', '--file', '/mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG/.datalad/config'] (cwd=/mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG)
[DEBUG  ] Finished ['git', 'config', '-z', '-l', '--show-origin', '--file', '/mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG/.datalad/config'] with status 0
[DEBUG  ] Determined class of decorated function: <class 'datalad.local.subdatasets.Subdatasets'>
[DEBUG  ] Resolved dataset to report on subdataset(s): /mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG
[DEBUG  ] Query subdatasets of None
[DEBUG  ] Query subdatasets underneath paths: [PosixPath('/mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG/Restin/rmegpreproc')]
[DEBUG  ] Determine what files match the query to work with
[DEBUG  ] Run ['git', 'annex', 'version', '--raw'] (cwd=None)
[DEBUG  ] Finished ['git', 'annex', 'version', '--raw'] with status 0
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', '-c', 'annex.merge-annex-branches=false', 'annex', 'find', '--not', '--in', '.', '--json', '--json-error-messages', '-c', 'annex.dotfiles=true', '--', 'Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat'] (cwd=/mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG)
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', '-c', 'annex.merge-annex-branches=false', 'annex', 'find', '--not', '--in', '.', '--json', '--json-error-messages', '-c', 'annex.dotfiles=true', '--', 'Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat'] with status 0
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'annex', 'get', '-c', 'annex.retry=3', '--json', '--json-error-messages', '--json-progress', '-c', 'annex.dotfiles=true', '--', 'Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat'] (cwd=/mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG)
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'annex', 'get', '-c', 'annex.retry=3', '--json', '--json-error-messages', '--json-progress', '-c', 'annex.dotfiles=true', '--', 'Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat'] with status 1
[DEBUG  ] received JSON result from annex: {'command': 'get', 'wanted': [], 'note': 'from datalad...\nUnable to access these remotes: datalad\n(Note that these git remotes have annex-ignore set: origin)', 'success': False, 'input': ['Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat'], 'key': 'MD5E-s279179120--7b464839e762e056ce874c877c88d17c.mat', 'error-messages': ['  RuntimeError(Failed to download from any of 1 locations)', '  RuntimeError(Failed to download from any of 1 locations)', '  RuntimeError(Failed to download from any of 1 locations)'], 'file': 'Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat'}
get(error): Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat (file) [RuntimeError(Failed to download from any of 1 locations)
RuntimeError(Failed to download from any of 1 locations)
RuntimeError(Failed to download from any of 1 locations)]
[DEBUG  ] could not perform all requested actions: IncompleteResultsError(Command did not complete successfully. 1 failed:
[{'action': 'get',
  'annexkey': 'MD5E-s279179120--7b464839e762e056ce874c877c88d17c.mat',
  'error_message': 'RuntimeError(Failed to download from any of 1 locations)\n'
                   'RuntimeError(Failed to download from any of 1 locations)\n'
                   'RuntimeError(Failed to download from any of 1 locations)',
  'path': '/mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG/Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat',
  'refds': '/mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG',
  'status': 'error',
  'type': 'file'}])
```
</details>

Thanks for looking into this! :)

**Comment by adswa** [comment]
hey, I can reproduce this. With the most recent, unreleased version of datalad I get a bit better error messages, and see

```
❱ DATALAD_hcp_s3_key_id=<mykey>  DATALAD_hcp_s3_secret_id=<mypass> datalad get HCP1200/100307/MEG/Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat
get(error): HCP1200/100307/MEG/Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat (file) [Failed to download from any of 1 locations [S3ResponseError: 403 Forbidden\n]
Failed to download from any of 1 locations [S3ResponseError: 403 Forbidden\n]
Failed to download from any of 1 locations [S3ResponseError: 403 Forbidden\n]]
action summary:
  get (error: 1, notneeded: 1)
```

Despite passwords that should be working. I haven't had time to look in more detail yet. Hopefully I can get to it over the Winter break.

**Comment by eduardosand** [comment]
Hello, I am having a similar problem. I can grab metadata with `datalad get -n dataset` but fails when I try to actually download, even when explicitly setting credentials as environmental variables; However, I don't get a RunTimeError.

results from datalad wt
[software_details.txt](https://github.com/datalad-datasets/human-connectome-project-openaccess/files/7817160/software_details.txt)
results from datalad -l debug
[debug.txt](https://github.com/datalad-datasets/human-connectome-project-openaccess/files/7817405/debug.txt)

Thank you for looking into this. Is it possible that this is due to the latest update to the s3 bucket? I know that the unprocessed 7T data was added to the bucket recently. https://groups.google.com/a/humanconnectome.org/g/hcp-announce/c/t78IBBSbwAc?pli=1
I only bring this up because I tried to write my own code using Boto3 to access the s3 bucket, but could only access metadata.

**Comment by bpoldrack** [comment]
FTR: I'm working on it. Apparently versioning was switched off with the S3 bucket which is why the dataset's requests (asking for a specific version of the files) come back with an 403 - Forbidden. This was likely done when data was added (see https://github.com/datalad-datasets/human-connectome-project-openaccess/issues/29). Dataset needs to be updated accordingly.

**Comment by cbedetti** [comment]
Hello,

I also have the same error. `datalad get` never ask me the credentials.

```
DATALAD_hcp_s3_key_id=<key> DATALAD_hcp_s3_secret_id=<secret> datalad get release-notes/ReleaseNotes.txt 
get(error): release-notes/ReleaseNotes.txt (file) [RuntimeError(Failed to download from any of 1 locations)                                       
RuntimeError(Failed to download from any of 1 locations)
RuntimeError(Failed to download from any of 1 locations)]
```

I know it doesn't add to the issue but I'm just letting you know that the problem still seems to be there.

**Comment by jajcayn** [comment]
Still the same error, even after the update...
I did run
`datalad update --merge`, just to be sure also `git pull`, the repository is up-to-date, but I am having the same error

**Comment by adswa** [comment]
Hey, thanks for trying so fast. Could you make sure that the specific subdataset you retrieve the data from is also updated? Those subdatasets will be the place that contain the new availability information. Because the changes were so wide-spread, it will be necessary to ``update --merge`` the complete dataset hierarchy of all datasets you have had installed (an ``datalad update --merge -r`` in the superdataset should do it), or clone the superdataset from here again.

For illustration, I still have the dataset that I used to verify the download issue [from above](https://github.com/datalad-datasets/human-connectome-project-openaccess/issues/30#issuecomment-999680035). In there, without an update of the subdataset, the error persists:
```
(handbook2) adina@muninn in ~/repos/data/human-connectome-project-openaccess on git:master
❱ DATALAD_hcp_s3_key_id=xxxxxxx DATALAD_hcp_s3_secret_id=xxxxxxx datalad get HCP1200/100307/MEG/Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat

get(error): HCP1200/100307/MEG/Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat (file) [Failed to download from any of 1 locations [S3ResponseError: 403 Forbidden\n]
Failed to download from any of 1 locations [S3ResponseError: 403 Forbidden\n]
Failed to download from any of 1 locations [S3ResponseError: 403 Forbidden\n]]
action summary:
  get (error: 1, notneeded: 1)
```

but after an update of this subdataset:

```
(handbook2) adina@muninn in ~/repos/data/human-connectome-project-openaccess on git:master
❱ datalad -C HCP1200/100307/MEG update --merge                              1 !
[INFO   ] Fetching updates for Dataset(/home/adina/repos/data/human-connectome-project-openaccess/HCP1200/100307/MEG) 
merge(ok): . (dataset) [Merged origin/master]
update.annex_merge(ok): . (dataset) [Merged annex branch]
update(ok): . (dataset)
action summary:
  merge (ok: 1)
  update (ok: 1)
  update.annex_merge (ok: 1)
(handbook2) adina@muninn in ~/repos/data/human-connectome-project-openaccess on git:master
❱ DATALAD_hcp_s3_key_id=xxxxxxxxxxxxxxxx DATALAD_hcp_s3_secret_id=xxxxxxxxxxx datalad get HCP1200/100307/MEG/Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat

get(ok): HCP1200/100307/MEG/Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat (file) [from datalad...]
action summary:
  get (notneeded: 1, ok: 1)
```

**Comment by jajcayn** [comment]
hey @adswa 
thanks for getting back to me..
unfortunately no, nothing helps..

I did `datalad update --merge -r` in the root of HCP dataset
I also tried `datalad -C HCP1200/100307/MEG update --merge`
both of them finished with 
```
[INFO   ] Fetching updates for Dataset(/mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG)
merge(ok): . (dataset) [Merged origin/master]
update.annex_merge(ok): . (dataset) [Merged annex branch]
update(ok): . (dataset)
action summary:
  merge (ok: 1)
  update (ok: 1)
  update.annex_merge (ok: 1)
```
or similar.. but ultimately, when I try to
```bash
DATALAD_hcp_s3_key_id=XXX DATALAD_hcp_s3_secret_id=XXX datalad -l debug get 100307_MEG_3-Restin_rmegpreproc.mat
```
I get
```
[DEBUG  ] Command line args 1st pass for DataLad 0.15.5. Parsed: Namespace() Unparsed: ['get', '100307_MEG_3-Restin_rmegpreproc.mat']
[DEBUG  ] Building doc for <class 'datalad.local.subdatasets.Subdatasets'>
[DEBUG  ] Building doc for <class 'datalad.core.distributed.clone.Clone'>
[DEBUG  ] Building doc for <class 'datalad.distribution.get.Get'>
[DEBUG  ] Parsing known args among ['/usr/bin/datalad', '-l', 'debug', 'get', '100307_MEG_3-Restin_rmegpreproc.mat']
[DEBUG  ] Run ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin'] (cwd=None)
[DEBUG  ] Finished ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin'] with status 0
[DEBUG  ] Determined class of decorated function: <class 'datalad.distribution.get.Get'>
[DEBUG  ] Resolved dataset to get content of <<['100307_MEG_3++21 chars++at']>>: /mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG
[DEBUG  ] Run ['git', 'config', '-z', '-l', '--show-origin'] (cwd=/mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG)
[DEBUG  ] Finished ['git', 'config', '-z', '-l', '--show-origin'] with status 0
[DEBUG  ] Run ['git', 'config', '-z', '-l', '--show-origin', '--file', '/mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG/.datalad/config'] (cwd=/mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG)
[DEBUG  ] Finished ['git', 'config', '-z', '-l', '--show-origin', '--file', '/mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG/.datalad/config'] with status 0
[DEBUG  ] Determined class of decorated function: <class 'datalad.local.subdatasets.Subdatasets'>
[DEBUG  ] Resolved dataset to report on subdataset(s): /mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG
[DEBUG  ] Query subdatasets of None
[DEBUG  ] Query subdatasets underneath paths: [PosixPath('/mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG/Restin/rmegpreproc')]
[DEBUG  ] Determine what files match the query to work with
[DEBUG  ] Run ['git', 'annex', 'version', '--raw'] (cwd=None)
[DEBUG  ] Finished ['git', 'annex', 'version', '--raw'] with status 0
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', '-c', 'annex.merge-annex-branches=false', 'annex', 'find', '--not', '--in', '.', '--json', '--json-error-messages', '-c', 'annex.dotfiles=true', '--', 'Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat'] (cwd=/mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG)
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', '-c', 'annex.merge-annex-branches=false', 'annex', 'find', '--not', '--in', '.', '--json', '--json-error-messages', '-c', 'annex.dotfiles=true', '--', 'Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat'] with status 0
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'annex', 'get', '-c', 'annex.retry=3', '--json', '--json-error-messages', '--json-progress', '-c', 'annex.dotfiles=true', '--', 'Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat'] (cwd=/mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG)
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'annex', 'get', '-c', 'annex.retry=3', '--json', '--json-error-messages', '--json-progress', '-c', 'annex.dotfiles=true', '--', 'Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat'] with status 1
[DEBUG  ] received JSON result from annex: {'command': 'get', 'wanted': [], 'note': 'from datalad...\nUnable to access these remotes: datalad\n(Note that these git remotes have annex-ignore set: origin)', 'success': False, 'input': ['Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat'], 'key': 'MD5E-s279179120--7b464839e762e056ce874c877c88d17c.mat', 'error-messages': ['  RuntimeError(Failed to download from any of 2 locations)', '  RuntimeError(Failed to download from any of 2 locations)', '  RuntimeError(Failed to download from any of 2 locations)'], 'file': 'Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat'}
get(error): Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat (file) [RuntimeError(Failed to download from any of 2 locations)
RuntimeError(Failed to download from any of 2 locations)
RuntimeError(Failed to download from any of 2 locations)]
[DEBUG  ] could not perform all requested actions: IncompleteResultsError(Command did not complete successfully. 1 failed:
[{'action': 'get',
  'annexkey': 'MD5E-s279179120--7b464839e762e056ce874c877c88d17c.mat',
  'error_message': 'RuntimeError(Failed to download from any of 2 locations)\n'
                   'RuntimeError(Failed to download from any of 2 locations)\n'
                   'RuntimeError(Failed to download from any of 2 locations)',
  'path': '/mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG/Restin/rmegpreproc/100307_MEG_3-Restin_rmegpreproc.mat',
  'refds': '/mnt/data/human-connectome-project-openaccess/HCP1200/100307/MEG',
  'status': 'error',
  'type': 'file'}])
```

**Comment by adswa** [comment]
hmmm, sorry to hear this... @mih is there anything that comes to your mind about this? @jajcayn posted his ``wtf`` [above](https://github.com/datalad-datasets/human-connectome-project-openaccess/issues/30#issuecomment-997467384) and everything looks recent to me. Could there be dependencies we haven't accounted for, e.g., to  [``AnnexRemote``](https://github.com/Lykos153/AnnexRemote)?

**Comment by bpoldrack** [comment]
@jajcayn 

> `DATALAD_hcp_s3_key_id=XXX DATALAD_hcp_s3_secret_id=XXX`

I think this is incorrect. Should be `DATALAD_CREDENTIAL_hcp__s3_key__id=XXX` and `DATALAD_CREDENTIAL_hcp__s3_secret__id=XXX` instead.

**Comment by bpoldrack** [comment]
Sorry for the noise. Both variants work indeed, so that's not the issue here.
